#define MICROPY_HW_BOARD_NAME "ESP32 (spiram) UD-PLANTER"
#define MICROPY_HW_MCU_NAME "ESP32"

//#define MICROPY_WRAP_MP_BINARY_OP (0)


//#define MICROPY_WRAP_MP_BINARY_OP(f) f
//#define MICROPY_WRAP_MP_EXECUTE_BYTECODE(f)  f
//#define MICROPY_WRAP_MP_LOAD_GLOBAL(f)  f
//#define MICROPY_WRAP_MP_LOAD_NAME(f)  f
//#define MICROPY_WRAP_MP_MAP_LOOKUP(f)  f
//#define MICROPY_WRAP_MP_OBJ_GET_TYPE(f)  f